version: '3'
services:
  web:
    build: .
    ports:
      - "3333:3333"
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: ["/cloud_sql_proxy",
              "-instances=skilled-bee-269209:us-east1:mysql=tcp:0.0.0.0:3306"]
    ports:
      - "3306:3306"
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - mysql_data:/var/lib/mysql
volumes:
  bundle:
  mysql_data: