FROM ruby:2.5.1
ENV LANG C.UTF-8
ENV RAILS_ENV production
RUN apt-get update -qq && apt-get install -y build-essential nodejs mysql-client
RUN mkdir /myapp
WORKDIR /myapp
ADD Gemfile Gemfile.lock /myapp/

RUN bundle install

ADD . /myapp

CMD \
    bundle exec rails db:migrate && \
    #bundle exec rake assets:precompile && \
    bundle exec rails s -p 3000 -b '0.0.0.0'